# Coolify docker compose - deploys web + worker
services:
  pyramid-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:4444/up"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 2
    #   start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    labels:
      - "coolify.managed=true"

  pyramid-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
      GEOCODER_API_KEY: ${GEOCODER_API_KEY}
    healthcheck:
      test: ["CMD", "pgrep", "-f", "bin/jobs"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 60s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    labels:
      - "coolify.managed=true"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.managed=true"

volumes:
  redis_data:
